use_frameworks!

platform :ios, '8.0'

target 'XKHttpNetworkHelper_Example' do
  pod 'XKHttpNetworkHelper', :path => '../'

  target 'XKHttpNetworkHelper_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
